### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by infality** [infality/implayer#1]
Things I may add when I find time/motivation:
- [ ] Improve error handling when downloading
- [ ] Song queue:
  - [ ] Actions to add songs to front/back of queue
  - [ ] Move and delete songs in the queue
- [x] Sort displayed songs by artist/song/duration
- [ ] Drag&Drop to reorder songs in playlist
- [ ] Keyboard navigation (select songs/playlists with keyboard, also map arrow keys)
- [x] Fix alternating row coloring when filtering
- [ ] Properly dispose threads when exiting application
- [ ] Support more unicode symbols
- [ ] Random playback
